#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

if [ -f "/tmp/leftwm-theme-down"]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

if [ -x "$(command -v picom)" ]; then
    picom -b &> /dev/null &
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v nitrogen)" ]; then
    WALLPAPERSPATH="~/system-config/config/nitrogen/wallpapers"
    nitrogen --restore &
    # nitrogen --save --head=0 --set-scaled $WALLPAPERSPATH/1920x1080/download\ \(4\)-1920x1080.jpeg &
    # nitrogen --save --head=1 --set-scaled $WALLPAPERSPATH/3840x2160/pexels-photo-1424246.jpeg  
    unset WALLPAPERSPATH
fi

if [ -x "$(command -v polybar)" ]; then
    $HOME/.config/polybar/launch-polybar.sh
fi
