vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gl", vim.cmd.GcLog)
vim.keymap.set("n", "<leader>gp", function() vim.cmd { cmd = "Git!", args = { "push" } } end)
vim.keymap.set("n", "<leader>gP", function() vim.cmd { cmd = "Git!", args = { "pull" } } end)
vim.keymap.set("n", "<leader>gPR", function() vim.cmd { cmd = "Git!", args = { "pull", "--rebase" } } end)
