require("after.plugin.colors")
require("after.plugin.fugitive")
require("after.plugin.harpoon")
require("after.plugin.lsp")
require("after.plugin.telescope")
require("after.plugin.treesitter")
require("after.plugin.undotree")
