require("plugins.packer")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.fugitive")
require("plugins.gitsigns")
-- require("plugins.harpoon")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.treesitter")
require("plugins.undotree")
