require("plugins.p_autopairs")
require("plugins.p_bufferline")
require("plugins.p_fugitive")
require("plugins.p_gitsigns")
require("plugins.p_gopher")
-- require("plugins.p_harpoon")
require("plugins.p_null_ls")
require("plugins.p_lsp")
require("plugins.p_cmp")
require("plugins.p_illuminate")
require("plugins.p_indent_blankline")
require("plugins.p_leap")
require("plugins.p_lualine")
require("plugins.p_nvim-tree")
-- require("plugins.p_prosession")
require("plugins.p_telescope")
require("plugins.p_toggleterm")
require("plugins.p_treesitter")
require("plugins.p_undotree")
require("plugins.p_which-key")
