-- Plugin for allowing me to have more clarification
-- on which parenthesis, square brackets and curly braces
-- start and end.

return {}
-- return {
--     "HiPhish/rainbow-delimiters.nvim",
--     config = function()
--         local rainbow_delimiters = require("rainbow-delimiters")
--
--         vim.g.rainbow_delimiters = {
--             strategy = {
--                 [""] = rainbow_delimiters.strategy["global"],
--                 vim = rainbow_delimiters.strategy["local"]
--             },
--             query = {
--                 [""] = "rainbow-delimiters",
--                 lua = "rainbow-blocks"
--             },
--             priority = {
--                 [''] = 110,
--                 lua = 210,
--             },
--             -- highlight = BASE.defaults.highlight_groups,
--             highlight = {
--                 "ColorColumn",
--                 "RainbowDelimiterRed",
--                 "RainbowDelimiterBlue",
--                 "RainbowDelimiterGreen",
--                 "RainbowDelimiterViolet",
--                 "RainbowDelimiterCyan",
--             }
--         }
--     end
-- }
